# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: resource-quota
spec:
  steps:
  - name: step-00
    try:
    - apply:
        file: 00-install.yaml
    - assert:
        file: 00-assert.yaml
  - catch:
    - events:
        namespace: $NAMESPACE
    name: step-01
    try:
    - apply:
        file: 01-create-pod.yaml
    - script:
        content: |
          set -e
          used_pods=$(kubectl get resourcequota test-quota -n $NAMESPACE -o jsonpath='{.status.used.pods}')
          test "$used_pods" -eq 1
