# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/configuration-chainsaw-v1alpha2.json
apiVersion: chainsaw.kyverno.io/v1alpha2
kind: Configuration
metadata:
  name: configuration
spec:
  templating:
    enabled: false
  timeouts:
    apply: 1h
    assert: 1h
    cleanup: 1h
    delete: 1h
    error: 1h
    exec: 1h
