# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/configuration-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: configuration
spec:
  template: false
  timeouts:
    apply: 30s
    assert: 60s
    cleanup: 30s
    delete: 15s
    error: 30s
    exec: 120s
