apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - ./e2e/pods
  - ./e2e/workloads
  - ./e2e/networking
  - ./e2e/configuration
  - ./e2e/scheduling
  - ./e2e/auth
  - ./e2e/policy
  - ./e2e/api
  - ./e2e/observability
