apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pdb
status:
  readyReplicas: 3
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
status:
  expectedPods: 3
  disruptionsAllowed: 1
