apiVersion: v1
kind: Pod
metadata:
  name: resource-set
spec:
  containers:
  - resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
status:
  phase: Running
---
apiVersion: v1
kind: Pod
metadata:
  name: resource-excessive
status:
  phase: Pending
