# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: restart-policy
spec:
  steps:
  - catch:
    - podLogs:
        name: restart-never
        tail: 20
    name: step-00
    try:
    - apply:
        file: 00-install.yaml
    - assert:
        file: 00-assert.yaml
  - catch:
    - podLogs:
        name: restart-onfailure
        tail: 20
    name: step-01
    try:
    - apply:
        file: 01-install.yaml
    - assert:
        timeout: 60s
        resource:
          apiVersion: v1
          kind: Pod
          metadata:
            name: restart-onfailure
          status:
            containerStatuses:
            - restartCount: 1
  - catch:
    - podLogs:
        name: restart-always
        tail: 20
    name: step-02
    try:
    - apply:
        file: 02-install.yaml
    - assert:
        timeout: 60s
        resource:
          apiVersion: v1
          kind: Pod
          metadata:
            name: restart-always
          status:
            containerStatuses:
            - restartCount: 1
