apiVersion: v1
kind: Pod
metadata:
  name: pod-projected-token
spec:
  restartPolicy: Never
  serviceAccountName: sa-with-token
  automountServiceAccountToken: false
  containers:
    - name: test
      image: busybox:1.37
      command: ["sh", "-c"]
      args:
        - |
          set -e
          test -f /var/run/secrets/custom/custom-token
      volumeMounts:
        - name: projected-token
          mountPath: /var/run/secrets/custom
          readOnly: true
  volumes:
    - name: projected-token
      projected:
        sources:
          - serviceAccountToken:
              path: custom-token
              audience: api.example.com
              expirationSeconds: 3600
