# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: pod-probes
spec:
  steps:
  - catch:
    - podLogs:
        name: liveness-http
        tail: 20
    name: step-00
    try:
    - apply:
        file: 00-install.yaml
    - assert:
        file: 00-assert.yaml
  - catch:
    - podLogs:
        name: readiness-file
        tail: 20
    name: step-01
    try:
    - apply:
        file: 01-install.yaml
    - assert:
        file: 01-assert.yaml
  - catch:
    - podLogs:
        name: startup-http
        tail: 20
    name: step-02
    try:
    - apply:
        file: 02-install.yaml
    - assert:
        file: 02-assert.yaml
