apiVersion: v1
kind: ServiceAccount
metadata:
  name: smoke-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: smoke-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smoke-binding
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smoke-config
---
apiVersion: v1
kind: Secret
metadata:
  name: smoke-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smoke-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-deploy
status:
  readyReplicas: 1
