apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c", "date >> /pvc/started.txt && date >> /scratch/started.txt"]
      volumeMounts:
        - name: data
          mountPath: /pvc
        - name: scratch
          mountPath: /scratch
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-pvc
    - name: scratch
      emptyDir: {}
