# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: configmap-mount
spec:
  description: Validates ConfigMap volume mount exposes data to pods as files
  steps:
  - name: create-and-verify-configmap-mount
    try:
    - apply:
        file: 00-install.yaml
    - assert:
        file: 00-assert.yaml
    catch:
    - podLogs:
        name: configmap-reader
        tail: 20
